### ISSUE TITLE
Support new Xcode 10 properties

### ISSUE THREAD

**Issue by pepibumur** [xcode-project-manager/xcodeproj#269]
## Context 🕵️‍♀️
Xcode 9 has introduced new attributes like file lists in build phases. We should add support for them.

**Comment by pepibumur** [comment]
This is what we'd need to add https://github.com/CocoaPods/Xcodeproj/commit/517e1f6d338acc0ed9b7b534428cda4882a4d570

**Comment by yonaskolb** [comment]
How about the parallel testing for schemes
