### ISSUE TITLE
Improve parsing errors

### ISSUE THREAD

**Issue by pepibumur** [xcode-project-manager/xcodeproj#98]
## Context 🕵️‍♀️
Right now, if the parsing fails for some reason, it throws an error saying that a property that was expected, wasn't there or it was in the wrong format. It'd be great to throw something more explicit like:

> We've found an element XXXX with a reference XXXX that is missing the property XXXX.

## What 🌱
Improve the error message.

## Proposal 🎉

> We've found an element XXXX with a reference XXXX that is missing the property XXXX. Your project might have got into an invalid state after a merging conflict. We recommend you to open it with Xcode, identify the issue and fix it before trying to open it with xcproj.

**Comment by pepibumur** [comment]
What do you think @xcodeswift/contributors

**Comment by toshi0383** [comment]
Error message should always be user-friendly.👌
But priority is low for now I guess. There is still a lot of formatting problems and potential SPM compatibility issue right now.

**Comment by pepibumur** [comment]
Definitively. I've updated the priority to low and removed it from the next milestone so that we can focus on all the formatting issues.

**Comment by pepibumur** [comment]
What do you mean by *"potential SPM compatibility issue"* btw?

**Comment by toshi0383** [comment]
I've seen this PR. https://github.com/xcodeswift/xcproj/pull/97
And I thought we might have this kind of compatibility issues on other type (`empty|library|executable|system-module` ) of SPM generated pbxproj.

**Comment by yonaskolb** [comment]
I wonder if SPM generated projects are worth creating fixes for at this time. SPM is still a work in progress, and the projects it generates have never been quite to spec. I don't doubt that will improve in the future though.
Are there use cases for reading SPM generated projects anyway?

**Comment by toshi0383** [comment]
XcodeGen's purpose is to generate, so there are no use case for reading.
But for example I have a tool which modifies xcodeproj, so I have to support SPM too.
https://github.com/toshi0383/xcconfig-extractor
